### PR TITLE
Bugfix for PE1

### LINKED ISSUE #152: Edit phone number error
**Describe the bug**

**To Reproduce**
1. key in 'edit 1 p/91234567546789765545678978675467897654 e/johndoe@example.com"
2. Error in side pane

**Expected behavior**
The full number should be displayed, but number is cut off

**Screenshots**

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#96]</sub>

### PR DESCRIPTION
**Pull request by elstonayx**
Resolves #152

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -11,8 +11,9 @@
 
 
     public static final String MESSAGE_PHONE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String PHONE_VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should be at least 3 digits long "
+                + "and at most 20 digits long";
+    public static final String PHONE_VALIDATION_REGEX = "\\d{3,20}";
```
Comment (linnnruoo) [inline src/main/java/seedu/address/model/person/Phone.java:16]: good i love it

**Review by linnnruoo — APPROVED** [review]
